tap "buo/cask-upgrade"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
cask "iterm2"
brew "autoconf"
brew "mackup"
brew "mas"
brew "autojump"
brew "bash"
brew "brew-cask-completion"
brew "coreutils"
brew "dnsmasq", restart_service: true
brew "ecm"
brew "ffmpeg"
brew "fliqlo"
brew "findutils"
brew "git"
brew "git-flow"
brew "gnupg"
brew "go"
brew "grc"
brew "handbrake"
brew "htop"
brew "httpd", restart_service: true
brew "httpie"
brew "httrack"
brew "hub"
brew "irssi"
brew "joe"
brew "libiconv"
brew "libyaml"
brew "mariadb", restart_service: true
brew "mkvtoolnix", link: false
brew "nvm"
brew "opencc"
brew "openldap"
brew "openvpn"
brew "pandoc"
brew "pandoc-citeproc"
brew "pandoc-crossref"
brew "putty"
brew "pyenv"
brew "rbenv"
brew "redis"
brew "rethinkdb"
brew "scrcpy"
brew "ssh-copy-id", link: true
brew "stow"
brew "terraform"
brew "trash"
brew "tree"
brew "unrar"
brew "wget"
brew "youtube-dl"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-git-prompt"
brew "zsh-navigation-tools"
brew "zsh-syntax-highlighting"
cask "4k-stogram"
cask "4k-video-downloader"
cask "4k-youtube-to-mp3"
cask "aegisub"
cask "alfred"
cask "android-platform-tools"
cask "anydesk"
cask "appcleaner"
cask "atom"
cask "baidunetdisk"
cask "battle-net"
cask "betterzip"
cask "beyond-compare"
cask "brackets"
cask "brave-browser"
cask "charles"
cask "cheatsheet"
#cask "cleanmymac"
cask "coconutbattery"
cask "couleurs"
cask "cyberduck"
cask "dash"
cask "db-browser-for-sqlite"
cask "dozer"
cask "dropbox"
cask "dynalist"
cask "evernote"
cask "firefox-developer-edition"
cask "flux"
cask "focus-booster"
cask "font-util"
cask "font-hack"
cask "font-noto-sans-cjk"
cask "font-noto-serif-cjk"
cask "font-roboto"
cask "font-source-code-pro"
cask "font-source-han-noto-cjk"
cask "font-sourcecodepro-nerd-font"
cask "font-ibm-plex"
cask "font-ibm-plex-mono"
cask "font-ibm-plex-sans"
cask "font-ibm-plex-sans-arabic"
cask "font-ibm-plex-sans-condensed"
cask "font-ibm-plex-sans-devanagari"
cask "font-ibm-plex-sans-hebrew"
cask "font-ibm-plex-sans-kr"
cask "font-ibm-plex-serif"
cask "font-ibm-plex-sans-thai-looped"
cask "font-ibm-plex-sans-thai"
cask "franz"
cask "gimp"
cask "gitter"
cask "gog-galaxy"
cask "google-chrome"
cask "handbrake"
cask "handshaker"
cask "iina"
# cask "imaging-edge"
cask "inkscape"
cask "itsycal"
cask "java"
cask "joplin"
cask "keka"
cask "kodi"
cask "laverna"
#cask "libreoffice"
#cask "libreoffice-language-pack"
cask "macdown"
cask "mailspring"
cask "marked"
cask "marta"
cask "mendeley"
cask "mkvtoolnix-app"
cask "mkvtools"
cask "mounty"
cask "neteasemusic"
cask "ngrok"
cask "notion"
cask "obs"
cask "openemu-experimental"
cask "openshot-video-editor"
cask "paw"
cask "protonvpn"
cask "qbittorrent"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-json"
cask "quicklookase"
cask "recordit"
cask "scribus"
cask "send-anywhere"
cask "sequel-pro"
cask "shotcut"
cask "simplenote"
# cask "sketch"
# cask "sketch-toolbox"
cask "skype"
cask "slack"
cask "sourcetrail"
cask "sourcetree"
cask "spectacle"
cask "spotify"
cask "steam"
cask "sublime-text"
cask "suspicious-package"
cask "switchhosts"
cask "telegram"
cask "textmate"
cask "tiled"
cask "tor-browser"
cask "typora"
# cask "unity"
cask "upic"
#cask "virtualbox"
#cask "virtualbox-extension-pack"
cask "visual-studio-code"
cask "vlc"
cask "vnote"
cask "vu"
cask "webpquicklook"
cask "webstorm"
cask "welly"
cask "workflowy"
cask "xquartz"
cask "zotero"
mas "Agenda", id: 1287445660
mas "Amphetamine", id: 937984704
mas "Apowersoft Screen Recorder", id: 1030681467
mas "Disk Speed Test", id: 425264550
mas "EzyCal", id: 1190243926
mas "FileSumo Pro", id: 1182711853
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "Magnet", id: 441258766
mas "Numbers", id: 409203825
mas "OmmWriter", id: 412347921
mas "Pages", id: 409201541
mas "QuickKey", id: 1142743710
mas "QuickLinks", id: 1200685619
mas "ToothFairy", id: 1191449274
mas "Xcode", id: 497799835
